name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  linting:
    name: linting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        run: cargo clippy  -- -D warnings
      - name: Formatting
        run: cargo fmt -- --check
      
  build:
    needs: linting
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.OS }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-cargo-cache-
      - name: Dependencies
        run: |
          cargo install cargo-llvm-cov
          cargo install cargo-audit
      - name: Build
        run: cargo build --verbose
      - name: Tests and Code Coverage
        run: cargo llvm-cov
      - name: Security Audit
        run: cargo audit

